stages:
  - lint
  - test

lint:
  image: golangci/golangci-lint:latest
  stage: lint
  script:
    - go mod download
    - go list ./...
    - golangci-lint run --timeout=10m

test:
  image: golang:1.24
  stage: test
  script:
    - go test ./...