// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: scrapper.proto

package scrapperpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScrapperService_RegisterChat_FullMethodName     = "/scrapper.ScrapperService/RegisterChat"
	ScrapperService_DeleteChat_FullMethodName       = "/scrapper.ScrapperService/DeleteChat"
	ScrapperService_AddLink_FullMethodName          = "/scrapper.ScrapperService/AddLink"
	ScrapperService_RemoveLink_FullMethodName       = "/scrapper.ScrapperService/RemoveLink"
	ScrapperService_RemoveLinksByTag_FullMethodName = "/scrapper.ScrapperService/RemoveLinksByTag"
	ScrapperService_ListLinks_FullMethodName        = "/scrapper.ScrapperService/ListLinks"
)

// ScrapperServiceClient is the client API for ScrapperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScrapperServiceClient interface {
	RegisterChat(ctx context.Context, in *ChatIdRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteChat(ctx context.Context, in *ChatIdRequest, opts ...grpc.CallOption) (*Empty, error)
	AddLink(ctx context.Context, in *AddLinkRequest, opts ...grpc.CallOption) (*Empty, error)
	RemoveLink(ctx context.Context, in *RemoveLinkRequest, opts ...grpc.CallOption) (*Empty, error)
	RemoveLinksByTag(ctx context.Context, in *RemoveLinksByTagRequest, opts ...grpc.CallOption) (*RemoveLinksByTagResponse, error)
	ListLinks(ctx context.Context, in *ListLinksRequest, opts ...grpc.CallOption) (*ListLinksResponse, error)
}

type scrapperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScrapperServiceClient(cc grpc.ClientConnInterface) ScrapperServiceClient {
	return &scrapperServiceClient{cc}
}

func (c *scrapperServiceClient) RegisterChat(ctx context.Context, in *ChatIdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ScrapperService_RegisterChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperServiceClient) DeleteChat(ctx context.Context, in *ChatIdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ScrapperService_DeleteChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperServiceClient) AddLink(ctx context.Context, in *AddLinkRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ScrapperService_AddLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperServiceClient) RemoveLink(ctx context.Context, in *RemoveLinkRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ScrapperService_RemoveLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperServiceClient) RemoveLinksByTag(ctx context.Context, in *RemoveLinksByTagRequest, opts ...grpc.CallOption) (*RemoveLinksByTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveLinksByTagResponse)
	err := c.cc.Invoke(ctx, ScrapperService_RemoveLinksByTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrapperServiceClient) ListLinks(ctx context.Context, in *ListLinksRequest, opts ...grpc.CallOption) (*ListLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLinksResponse)
	err := c.cc.Invoke(ctx, ScrapperService_ListLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScrapperServiceServer is the server API for ScrapperService service.
// All implementations must embed UnimplementedScrapperServiceServer
// for forward compatibility.
type ScrapperServiceServer interface {
	RegisterChat(context.Context, *ChatIdRequest) (*Empty, error)
	DeleteChat(context.Context, *ChatIdRequest) (*Empty, error)
	AddLink(context.Context, *AddLinkRequest) (*Empty, error)
	RemoveLink(context.Context, *RemoveLinkRequest) (*Empty, error)
	RemoveLinksByTag(context.Context, *RemoveLinksByTagRequest) (*RemoveLinksByTagResponse, error)
	ListLinks(context.Context, *ListLinksRequest) (*ListLinksResponse, error)
	mustEmbedUnimplementedScrapperServiceServer()
}

// UnimplementedScrapperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScrapperServiceServer struct{}

func (UnimplementedScrapperServiceServer) RegisterChat(context.Context, *ChatIdRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterChat not implemented")
}
func (UnimplementedScrapperServiceServer) DeleteChat(context.Context, *ChatIdRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChat not implemented")
}
func (UnimplementedScrapperServiceServer) AddLink(context.Context, *AddLinkRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddLink not implemented")
}
func (UnimplementedScrapperServiceServer) RemoveLink(context.Context, *RemoveLinkRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveLink not implemented")
}
func (UnimplementedScrapperServiceServer) RemoveLinksByTag(context.Context, *RemoveLinksByTagRequest) (*RemoveLinksByTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveLinksByTag not implemented")
}
func (UnimplementedScrapperServiceServer) ListLinks(context.Context, *ListLinksRequest) (*ListLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLinks not implemented")
}
func (UnimplementedScrapperServiceServer) mustEmbedUnimplementedScrapperServiceServer() {}
func (UnimplementedScrapperServiceServer) testEmbeddedByValue()                         {}

// UnsafeScrapperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScrapperServiceServer will
// result in compilation errors.
type UnsafeScrapperServiceServer interface {
	mustEmbedUnimplementedScrapperServiceServer()
}

func RegisterScrapperServiceServer(s grpc.ServiceRegistrar, srv ScrapperServiceServer) {
	// If the following call panics, it indicates UnimplementedScrapperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScrapperService_ServiceDesc, srv)
}

func _ScrapperService_RegisterChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).RegisterChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperService_RegisterChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).RegisterChat(ctx, req.(*ChatIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperService_DeleteChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).DeleteChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperService_DeleteChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).DeleteChat(ctx, req.(*ChatIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperService_AddLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).AddLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperService_AddLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).AddLink(ctx, req.(*AddLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperService_RemoveLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).RemoveLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperService_RemoveLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).RemoveLink(ctx, req.(*RemoveLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperService_RemoveLinksByTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLinksByTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).RemoveLinksByTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperService_RemoveLinksByTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).RemoveLinksByTag(ctx, req.(*RemoveLinksByTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrapperService_ListLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).ListLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrapperService_ListLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).ListLinks(ctx, req.(*ListLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScrapperService_ServiceDesc is the grpc.ServiceDesc for ScrapperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScrapperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scrapper.ScrapperService",
	HandlerType: (*ScrapperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterChat",
			Handler:    _ScrapperService_RegisterChat_Handler,
		},
		{
			MethodName: "DeleteChat",
			Handler:    _ScrapperService_DeleteChat_Handler,
		},
		{
			MethodName: "AddLink",
			Handler:    _ScrapperService_AddLink_Handler,
		},
		{
			MethodName: "RemoveLink",
			Handler:    _ScrapperService_RemoveLink_Handler,
		},
		{
			MethodName: "RemoveLinksByTag",
			Handler:    _ScrapperService_RemoveLinksByTag_Handler,
		},
		{
			MethodName: "ListLinks",
			Handler:    _ScrapperService_ListLinks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scrapper.proto",
}
