// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/gRPC/bot.proto

package botpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TgChatIds     []int64                `protobuf:"varint,3,rep,packed,name=tg_chat_ids,json=tgChatIds,proto3" json:"tg_chat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkUpdateRequest) Reset() {
	*x = LinkUpdateRequest{}
	mi := &file_api_gRPC_bot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUpdateRequest) ProtoMessage() {}

func (x *LinkUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gRPC_bot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUpdateRequest.ProtoReflect.Descriptor instead.
func (*LinkUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_gRPC_bot_proto_rawDescGZIP(), []int{0}
}

func (x *LinkUpdateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LinkUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LinkUpdateRequest) GetTgChatIds() []int64 {
	if x != nil {
		return x.TgChatIds
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_gRPC_bot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_gRPC_bot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_gRPC_bot_proto_rawDescGZIP(), []int{1}
}

var File_api_gRPC_bot_proto protoreflect.FileDescriptor

const file_api_gRPC_bot_proto_rawDesc = "" +
	"\n" +
	"\x12api/gRPC/bot.proto\x12\x03bot\"g\n" +
	"\x11LinkUpdateRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\vtg_chat_ids\x18\x03 \x03(\x03R\ttgChatIds\"\a\n" +
	"\x05Empty2>\n" +
	"\n" +
	"BotService\x120\n" +
	"\n" +
	"SendUpdate\x12\x16.bot.LinkUpdateRequest\x1a\n" +
	".bot.EmptyB\x15Z\x13./pkg/api/bot;botpbb\x06proto3"

var (
	file_api_gRPC_bot_proto_rawDescOnce sync.Once
	file_api_gRPC_bot_proto_rawDescData []byte
)

func file_api_gRPC_bot_proto_rawDescGZIP() []byte {
	file_api_gRPC_bot_proto_rawDescOnce.Do(func() {
		file_api_gRPC_bot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gRPC_bot_proto_rawDesc), len(file_api_gRPC_bot_proto_rawDesc)))
	})
	return file_api_gRPC_bot_proto_rawDescData
}

var file_api_gRPC_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_gRPC_bot_proto_goTypes = []any{
	(*LinkUpdateRequest)(nil), // 0: bot.LinkUpdateRequest
	(*Empty)(nil),             // 1: bot.Empty
}
var file_api_gRPC_bot_proto_depIdxs = []int32{
	0, // 0: bot.BotService.SendUpdate:input_type -> bot.LinkUpdateRequest
	1, // 1: bot.BotService.SendUpdate:output_type -> bot.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_gRPC_bot_proto_init() }
func file_api_gRPC_bot_proto_init() {
	if File_api_gRPC_bot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gRPC_bot_proto_rawDesc), len(file_api_gRPC_bot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gRPC_bot_proto_goTypes,
		DependencyIndexes: file_api_gRPC_bot_proto_depIdxs,
		MessageInfos:      file_api_gRPC_bot_proto_msgTypes,
	}.Build()
	File_api_gRPC_bot_proto = out.File
	file_api_gRPC_bot_proto_goTypes = nil
	file_api_gRPC_bot_proto_depIdxs = nil
}
